### ISSUE TITLE
Modificar modelo de inscripción para aceptar información adicional de inscripciones

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/inscripcion_crud#11]
El modelo debe ajustarse para aceptar información adicional teniendo en cuenta el tipo de inscripción que se esta tratando de registrar.
- [x] El modelo permite almacenar información de reintegros.
- [x] El modelo permite almacenar información de transferencias internas. 
- [x] El modelo permite almacenar información de transferencias externas.

**Comment by JuanPiedrahita** [comment]
Se agrega [v_11](https://drive.google.com/drive/folders/1C9_DMszPu1JxIvopfGYvjY0XkFBqS3Hc?usp=sharing) del modelo de inscripciones, se hacen los siguientes ajustes:
- Se incluye tabla para reintegros.
- Se incluye tabla para transferencias (Internas y externas).
- Se incluye tala para inscripcion_pregrado (Permite almacenar información del icfes del aspirante).

**Comment by fabianbarreto02** [comment]
Se agrega tabla adicional para el manejo de informacion adicional de la infrmacion en inscripciones de posgrado.

![inscripcionV12](https://user-images.githubusercontent.com/43799065/63529155-dacf4c80-c4c9-11e9-9390-7cb42bc99356.png)
