### ISSUE TITLE
Ejecución de pruebas con pipeline de drone en ambiente de preproduccion (test)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/inscripcion_crud#15]
Se debe realizar la configuracion de los ambiente de despliegue tanto en en desarrollo (Jenkins), y el ambiente de preproducción (drone), para esto debe configurar el pipeline del api y configurar todas archivos necesarios, la issue debe cumplir con los siguiente requerimientos:

- [x] Realizar pruebas en el servidor local con el sistema CI Jenkins, revisando que ejectivamente funcione las pruebas unitarias.
- [ ] Realizar pruebas en el servidor prepodución (amazon) con el sistema CI drone, revisando que ejectivamente funcione las pruebas unitarias.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Para el desarrollo de issue se inicia con con la verificación de las pruebas unitarias establecidas en la [issue](https://github.com/udistrital/core_crud/issues/3) en el ambiente de desarrollo sobre Jenkins, se anexa imagen donde se observa las pruebas unitarias realizadas en el despliegue del api Inscripciones_crud.

![2019-08-28](https://user-images.githubusercontent.com/43799065/64048123-71d57d80-cb36-11e9-990e-0ee107702bd4.jpeg)

**Comment by fabianbarreto02** [comment]
La consola de jenkis no maneja codigo de colores, es por eso que mientras la ejecución de pruebas salen los codigos de colores de la consola.

**Comment by fabianbarreto02** [comment]
Se configura el pipeline drone.yml en la [rama](https://github.com/udistrital/inscripcion_crud/tree/nuevo_modelo) para el despliegue en el ambiente de preproducción debe realizar el despliegue necesario en amazon, por motivos del daño presentado en el servidor local HADES, el arquitecto no pudo realizar el despliegue necesario para correr las prubas unitarias en preproduccion.

**Comment by fabianbarreto02** [comment]
Pendiente revisión por parte de la lider técnica : @mafeave

**Comment by mafeave** [comment]
Queda pendiente revisión con @fernandotower en el ambiente de preproducción (test), pendiente kanban.
