### ISSUE TITLE
Crear reporte en SpagoBi del listado de aspirantes por proyecto

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/inscripcion_crud#16]
Crear reporte en spagobi que permita consultar el listado de los aspirantes por proyecto curricular.

**Comment by JuanPiedrahita** [comment]
@mafeave  por favor referenciar información necesaria para crear el reporte.

**Comment by mafeave** [comment]
Se anexa explicación para generar reporte con [Knowage](http://www.aiknow.info/2018/03/07/knowage-create-data-reports-with-birt/)

Dirección de [SpagoBI](https://intelligentia.udistrital.edu.co:8443/SpagoBI/servlet/AdapterHTTP?PAGE=LoginPage&NEW_SESSION=TRUE), consultar credenciales de acceso con @corio27

**Comment by JuanPiedrahita** [comment]
Se reciben credenciales y se verifican accesos al sistema.

**Comment by JuanPiedrahita** [comment]
SE realizará analisis de ocmo utilziar las herramientas

**Comment by JuanPiedrahita** [comment]
Se crea consulta para reporte
select 
	i.id inscripcion_id,
	p.primer_nombre||' '||p.segundo_nombre||' '||p.primer_apellido||' '||p.segundo_apellido nombre,
	e.nombre estado,
	pa.nombre proyecto,
	pe.nombre periodo
from 
	inscripcion.inscripcion i,
	inscripcion.estado_inscripcion e,
	core_new.persona p,
	programa_academico.programa_academico pa,
	core_new.periodo pe
where
	pe.id = i.periodo_id
	and	pa.id = i.programa_academico_id
	and	e.id = i.estado_inscripcion_id
	and	p.id = i.persona_id
	and i.periodo_id = ?
	and i.programa_academico_id = ?

**Comment by JuanPiedrahita** [comment]
Se crea [proyecto ](https://drive.google.com/drive/folders/1AyuXVWdFAhZqgvkGry2TFnL1C4t7Hr_t?usp=sharing)para el reporte

**Comment by JuanPiedrahita** [comment]
Se crea reporte y se muestra a lider tecnico @mafeave .

Se adjuntan evidencias de funcionamiento y despliegue en Spago.

![imagen](https://user-images.githubusercontent.com/25555966/64210261-6c46a300-ce68-11e9-830f-735c8d971421.png)

**Comment by mafeave** [comment]
Se revisa reporte en SpagoBI, el cual lista los inscritos por proyecto y periodo académico. Se da por finalizada la tarea.
Pendiente revisar con @FaustoPuerto formato del reporte.
