### ISSUE TITLE
Pruebas unitarias API CRUD de inscripcion - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/inscripcion_crud#19]
Se debe desarrollar las pruebas unitarias para todos los controladores del API,  la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar los scripst de test para cada controlador.
- [x] Realizar los test donde se evidencie el correcto funcionamiento de los controladores.
- [x] Realizar las pruebas con la libreria Godog.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo.

**Comment by fabianbarreto02** [comment]
![imagen](https://user-images.githubusercontent.com/43799065/67713340-a7aaad00-f993-11e9-94cf-46d77ad15c53.png)

**Comment by fabianbarreto02** [comment]
![imagen](https://user-images.githubusercontent.com/43799065/67714207-67e4c500-f995-11e9-9bce-597ba204c85a.png)

**Comment by fabianbarreto02** [comment]
![imagen](https://user-images.githubusercontent.com/43799065/67716982-d7a97e80-f99a-11e9-86b9-0931545c27de.png)

**Comment by fabianbarreto02** [comment]
![imagen](https://user-images.githubusercontent.com/43799065/67717802-6c60ac00-f99c-11e9-8c13-f6ff1e655785.png)

**Comment by fabianbarreto02** [comment]
Se llega a la conclución que a nivel de API CRUD no es necesario realizar pruebas a controladores no parametricos, ps se romperia la generalidad de las pruebas, por este movito se da por finalizada la tarea, se espera revisón por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Verificadas las pruebas, se da por finalizada la tarea.
