### ISSUE TITLE
Agregar un tipo de inscripción: nuevo/primer semestre y Generación E - 2 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/inscripcion_crud#35]
Se debe realizar el migrations para realizar la insercion de estos dos tipos de inscripcion:

- [x] Nuevo/primer semestre para nivel de pregrado y nivel posgrado

- [x] Generación E (antiguo ser pilo paga)

Lider técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de migrations.

**Comment by fabianbarreto02** [comment]
Ajuste realizado en el cliente para ordenar los tipos de inscripciones por mayor demanda [commit](https://github.com/udistrital/sga_cliente/commit/dd5d9c04a74b6e49777d2e2cabd7fda570fb2e8a)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue se espera revisión técnica por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica migración de los nuevos tipos de inscripción y la carga de los tipos de inscripción de acuerdo al campo NumeroOrden en el formulario de inscripción
![Captura de pantalla de 2020-01-13 19-23-13](https://user-images.githubusercontent.com/14035745/72303181-62b12100-363a-11ea-914f-fa1749cb4e44.png)
