### ISSUE TITLE
realizar ajustes sobre la rama feature/integracion master para desplegar en rama propia de planestic

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/inscripcion_crud#65]
se requiere realizar los ajustes ya socializados para que los pasos de drone se ejecuten exitosamente, pero en este caso se usara [la plantilla de drone para la rama personalizada de planestic](https://github.com/udistrital/financiera_documentacion/issues/210) .

adicionalmente se requiere eliminar la carpeta `.scannerwork`

**Comment by jevilla94** [comment]
@BOTOOM @jevilla94 @miguerpe @neconoe @planesticud 

Cordial saludo se realizaron los ajustes de rutas para comunicación udistrital y modificación de archivo drone.yml, se generó un error en uno de los pasos pero se ajusta en el siguiente commit

https://github.com/udistrital/inscripcion_crud/commit/4f119fa43c8d2f9d9604268d477cb1aeeeaeeb89
https://github.com/udistrital/inscripcion_crud/commit/f58137e9ef6fa8a0eee49b9de295f7357b5ab22f
