### ISSUE TITLE
Ajustar modelo de inscripcion para contemplar campo con puntaje total y cupos de carrera

### ISSUE THREAD

**Issue by mafeave** [udistrital/inscripcion_crud#9]
Se debe ajustar el modelo de datos de inscripcion para almacenar un campo con el puntaje total asignado a un aspirante y los cupos para la selección de admitidos por dependencia.

**Comment by mafeave** [comment]
Se agrega campo de puntaje_total en la tabla inscripcion del modelo de datos de inscripcion.

**Comment by mafeave** [comment]
Se propone la creación de la siguiente tabla:
![image](https://user-images.githubusercontent.com/14035745/62046371-5c82d180-b1cd-11e9-89e3-80b04a3b00de.png)

**Comment by mafeave** [comment]
Se debe evaluar si sería mejor dejarlo como un atributo de la tabla calendario_evento del esquema de evento:
![image](https://user-images.githubusercontent.com/14035745/62047305-c4d2b280-b1cf-11e9-932d-5a4f5799270f.png)

**Comment by mafeave** [comment]
De acuerdo a la revisión de @jairolh  se aprueba la agregación de la tabla cupos_por_dependencia en el esquema de evaluacion_inscripcion

**Comment by fabianbarreto02** [comment]
Se agrega la tabla cupos_por_dependencia en el esquema de evaluación_inscripcion para el manejo de los cupos 

![evaluacion_admisionV2](https://user-images.githubusercontent.com/43799065/63532454-5502cf80-c4d0-11e9-8c4f-833eeb6ad2b5.png)

**Comment by jairolh** [comment]
Se verifica la corrección de los ajustes solicitados, sin embargo se identifica que falta el mensaje de la relación de los campos con otros esquemas.
